/**
 * ========== RECIPE SEEDER WITH 20 RECIPES PER CATEGORY ==========
 * Seeds 80 quality recipes supporting all 9 features
 * - 20 Breakfast recipes
 * - 20 Lunch recipes
 * - 20 Dinner recipes
 * - 20 Snack recipes
 *
 * Usage: npm run seed:recipes
 */

const Recipe = require("./models/Recipe");
const User = require("./models/User");
const mongoose = require("mongoose");
const dotenv = require("dotenv");

dotenv.config();

const RECIPES = [
  // ==================== BREAKFAST - 20 RECIPES ====================
  {
    title: "Aloo Parathas",
    category: "Breakfast",
    description: "Flatbread stuffed with spiced potatoes.",
    image: "https://images.unsplash.com/photo-1605521209583-75d256e5caf1?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 30,
    cookTime: 20,
    benefits: "Energy-rich comfort food",
    equipment: ["Stovetop"],
    steps: [
      {
        stepNumber: 1,
        description: "Mix whole wheat flour with water and salt",
      },
      { stepNumber: 2, description: "Boil potatoes and mash with cumin seeds" },
      { stepNumber: 3, description: "Rest dough for 20 minutes" },
      { stepNumber: 4, description: "Roll dough and fill with potato mixture" },
      { stepNumber: 5, description: "Cook on hot tawa" },
      { stepNumber: 6, description: "Apply ghee and flip" },
      { stepNumber: 7, description: "Serve hot with yogurt" },
    ],
  },
  {
    title: "Chole Bhature",
    category: "Breakfast",
    description: "Fluffy deep-fried bread with spiced chickpea curry.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North India",
    difficulty: "Hard",
    servings: 4,
    prepTime: 240,
    cookTime: 45,
    benefits: "High in protein and fiber",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak white chickpeas overnight" },
      { stepNumber: 2, description: "Make dough with maida flour and yogurt" },
      { stepNumber: 3, description: "Ferment dough for 6 hours" },
      { stepNumber: 4, description: "Pressure cook chickpeas" },
      { stepNumber: 5, description: "Prepare curry with spices" },
      { stepNumber: 6, description: "Deep fry dough at 170°C" },
      { stepNumber: 7, description: "Serve with chickpea curry" },
    ],
  },
  {
    title: "Dosa",
    category: "Breakfast",
    description: "Crispy fermented rice and lentil crepe.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 480,
    cookTime: 30,
    benefits: "Digestible and protein-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak rice and urad dal for 8 hours" },
      { stepNumber: 2, description: "Add fenugreek seeds to dal" },
      { stepNumber: 3, description: "Grind into smooth batter" },
      { stepNumber: 4, description: "Mix and ferment for 8 hours" },
      { stepNumber: 5, description: "Heat tawa and apply oil" },
      { stepNumber: 6, description: "Spread batter layer" },
      { stepNumber: 7, description: "Cook till crispy and serve" },
    ],
  },
  {
    title: "Idli",
    category: "Breakfast",
    description: "Steamed soft rice and lentil cakes.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 480,
    cookTime: 20,
    benefits: "Light and easy to digest",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak rice and urad dal for 6 hours" },
      { stepNumber: 2, description: "Grind into smooth batter" },
      { stepNumber: 3, description: "Add salt and fenugreek seeds" },
      { stepNumber: 4, description: "Ferment for 8-10 hours" },
      { stepNumber: 5, description: "Pour batter into molds" },
      { stepNumber: 6, description: "Steam for 8-10 minutes" },
      { stepNumber: 7, description: "Serve with sambar and chutney" },
    ],
  },
  {
    title: "Upma",
    category: "Breakfast",
    description: "Savory semolina porridge with vegetables.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    benefits: "Quick energy source",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat ghee and add mustard seeds" },
      { stepNumber: 2, description: "Add vegetables and sauté" },
      { stepNumber: 3, description: "Add semolina and roast" },
      { stepNumber: 4, description: "Pour water slowly" },
      { stepNumber: 5, description: "Stir continuously" },
      { stepNumber: 6, description: "Cook on low heat" },
      { stepNumber: 7, description: "Serve hot with pickle" },
    ],
  },
  {
    title: "Pav Bhaji",
    category: "Breakfast",
    description: "Spiced potato curry with bread.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "West India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    benefits: "Energy-rich breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Boil and mash potatoes" },
      { stepNumber: 2, description: "Heat oil and add spice blend" },
      { stepNumber: 3, description: "Add mashed vegetables" },
      { stepNumber: 4, description: "Cook for 15 minutes" },
      { stepNumber: 5, description: "Toast bread on griddle" },
      { stepNumber: 6, description: "Apply butter" },
      { stepNumber: 7, description: "Serve with curry" },
    ],
  },
  {
    title: "Avial",
    category: "Breakfast",
    description: "Mixed vegetables in coconut gravy.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "South India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Vegetable-rich breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cut vegetables uniformly" },
      { stepNumber: 2, description: "Boil vegetables halfway" },
      { stepNumber: 3, description: "Grind coconut with cumin" },
      { stepNumber: 4, description: "Mix coconut paste" },
      { stepNumber: 5, description: "Add turmeric and salt" },
      { stepNumber: 6, description: "Temper with oil" },
      { stepNumber: 7, description: "Serve hot with rice" },
    ],
  },
  {
    title: "Puttu",
    category: "Breakfast",
    description: "Cylindrical steamed cake with coconut.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    benefits: "Light steamed food",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Mix rice flour with salt" },
      { stepNumber: 2, description: "Add grated coconut" },
      { stepNumber: 3, description: "Mix water to breadcrumb texture" },
      { stepNumber: 4, description: "Fill mold with layers" },
      { stepNumber: 5, description: "Insert in puttu kudam" },
      { stepNumber: 6, description: "Steam for 5-7 minutes" },
      { stepNumber: 7, description: "Push out and serve" },
    ],
  },
  {
    title: "Poha",
    category: "Breakfast",
    description: "Flattened rice with peanuts.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "Central India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    benefits: "Quick and nutritious",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Rinse flattened rice" },
      { stepNumber: 2, description: "Heat oil with mustard seeds" },
      { stepNumber: 3, description: "Add peanuts and chili" },
      { stepNumber: 4, description: "Add onions" },
      { stepNumber: 5, description: "Add drained rice" },
      { stepNumber: 6, description: "Mix well" },
      { stepNumber: 7, description: "Serve with lemon" },
    ],
  },
  {
    title: "Eggs Benedict",
    category: "Breakfast",
    description: "Poached eggs with hollandaise on toast.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "Europe",
    difficulty: "Hard",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Protein-rich breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Prepare hollandaise sauce" },
      { stepNumber: 2, description: "Toast English muffins" },
      { stepNumber: 3, description: "Layer ham on muffins" },
      { stepNumber: 4, description: "Poach eggs" },
      { stepNumber: 5, description: "Place egg on ham" },
      { stepNumber: 6, description: "Drizzle sauce" },
      { stepNumber: 7, description: "Garnish with paprika" },
    ],
  },
  {
    title: "Shakshuka",
    category: "Breakfast",
    description: "Eggs poached in spiced tomato sauce.",
    image: "https://images.unsplash.com/photo-1585938389335-a9e9b7aad356?w=600",
    state: "Middle East",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    benefits: "Protein-rich egg dish",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat oil and sauté onions" },
      { stepNumber: 2, description: "Add garlic and cumin" },
      { stepNumber: 3, description: "Add tomato sauce" },
      { stepNumber: 4, description: "Create wells for eggs" },
      { stepNumber: 5, description: "Crack eggs carefully" },
      { stepNumber: 6, description: "Cover and cook" },
      { stepNumber: 7, description: "Serve with pita bread" },
    ],
  },
  {
    title: "Pancakes",
    category: "Breakfast",
    description: "Fluffy stacked breakfast cakes.",
    image: "https://images.unsplash.com/photo-1585935924455-c7a6e54ac002?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    benefits: "Fun breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Mix flour and baking powder" },
      { stepNumber: 2, description: "Whisk wet ingredients" },
      { stepNumber: 3, description: "Combine ingredients gently" },
      { stepNumber: 4, description: "Heat griddle" },
      { stepNumber: 5, description: "Pour batter" },
      { stepNumber: 6, description: "Cook till golden" },
      { stepNumber: 7, description: "Serve with syrup" },
    ],
  },
  {
    title: "Khichdi",
    category: "Breakfast",
    description: "Comfort rice and lentil porridge.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 25,
    benefits: "Easy to digest",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak rice and dal" },
      { stepNumber: 2, description: "Heat ghee" },
      { stepNumber: 3, description: "Add rice and dal" },
      { stepNumber: 4, description: "Pour water" },
      { stepNumber: 5, description: "Boil and reduce heat" },
      { stepNumber: 6, description: "Cook covered" },
      { stepNumber: 7, description: "Serve with ghee" },
    ],
  },
  {
    title: "Soufflé",
    category: "Breakfast",
    description: "Fluffy baked cheese creation.",
    image: "https://images.unsplash.com/photo-1585938389335-a9e9b7aad356?w=600",
    state: "Europe",
    difficulty: "Hard",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    benefits: "Light and elegant",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Separate eggs" },
      { stepNumber: 2, description: "Make roux" },
      { stepNumber: 3, description: "Add milk and cheese" },
      { stepNumber: 4, description: "Beat egg whites" },
      { stepNumber: 5, description: "Fold gently" },
      { stepNumber: 6, description: "Pour into ramekins" },
      { stepNumber: 7, description: "Bake at 190°C" },
    ],
  },
  {
    title: "Dahi Vada",
    category: "Breakfast",
    description: "Lentil fritters soaked in yogurt.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "East India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 240,
    cookTime: 20,
    benefits: "Protein-rich and cool",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak urad dal overnight" },
      { stepNumber: 2, description: "Grind into thick batter" },
      { stepNumber: 3, description: "Beat for 5 minutes" },
      { stepNumber: 4, description: "Deep fry portions" },
      { stepNumber: 5, description: "Soak in warm water" },
      { stepNumber: 6, description: "Prepare sweetened yogurt" },
      { stepNumber: 7, description: "Mix and serve chilled" },
    ],
  },
  {
    title: "Uttappa",
    category: "Breakfast",
    description: "Thick South Indian rice pancake.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 480,
    cookTime: 25,
    benefits: "Versatile breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Prepare dosa batter" },
      { stepNumber: 2, description: "Heat griddle" },
      { stepNumber: 3, description: "Pour thick batter" },
      { stepNumber: 4, description: "Add vegetables on top" },
      { stepNumber: 5, description: "Cook bottom side" },
      { stepNumber: 6, description: "Flip carefully" },
      { stepNumber: 7, description: "Serve hot with chutney" },
    ],
  },
  {
    title: "Medu Vada",
    category: "Breakfast",
    description: "Donut-shaped fried lentil snack.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 240,
    cookTime: 25,
    benefits: "Crispy and savory",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak urad dal overnight" },
      { stepNumber: 2, description: "Grind to fluffy batter" },
      { stepNumber: 3, description: "Add salt and pepper" },
      { stepNumber: 4, description: "Heat oil for frying" },
      { stepNumber: 5, description: "Shape into rings" },
      { stepNumber: 6, description: "Fry till golden" },
      { stepNumber: 7, description: "Serve with sambar" },
    ],
  },
  {
    title: "Methi Thepla",
    category: "Breakfast",
    description: "Spiced fenugreek leaf flatbread.",
    image: "https://images.unsplash.com/photo-1605521209583-75d256e5caf1?w=600",
    state: "West India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 20,
    benefits: "Iron-rich breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Chop fenugreek leaves" },
      { stepNumber: 2, description: "Mix with flour and spices" },
      { stepNumber: 3, description: "Add yogurt and water" },
      { stepNumber: 4, description: "Rest dough" },
      { stepNumber: 5, description: "Roll thin circles" },
      { stepNumber: 6, description: "Cook on hot tawa" },
      { stepNumber: 7, description: "Apply ghee and serve" },
    ],
  },
  {
    title: "Breakfast Burrito",
    category: "Breakfast",
    description: "Tortilla wrapped with eggs and vegetables.",
    image: "https://images.unsplash.com/photo-1585235926794-1b51d7e41732?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Complete meal wrap",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Scramble eggs with vegetables" },
      { stepNumber: 2, description: "Cook bacon" },
      { stepNumber: 3, description: "Warm tortillas" },
      { stepNumber: 4, description: "Arrange ingredients" },
      { stepNumber: 5, description: "Add salsa and cream" },
      { stepNumber: 6, description: "Roll tightly" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },

  // ==================== LUNCH - 20 RECIPES ====================
  {
    title: "Sambar",
    category: "Lunch",
    description: "Tangy vegetable stew with lentils.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 45,
    benefits: "High in fiber",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cook toor dal" },
      { stepNumber: 2, description: "Chop vegetables" },
      { stepNumber: 3, description: "Add vegetables to dal" },
      { stepNumber: 4, description: "Add tamarind paste" },
      { stepNumber: 5, description: "Simmer for 20 minutes" },
      { stepNumber: 6, description: "Temper with spices" },
      { stepNumber: 7, description: "Serve with rice" },
    ],
  },
  {
    title: "Chana Masala",
    category: "Lunch",
    description: "Spiced chickpea curry.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    benefits: "High protein",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat oil and add cumin" },
      { stepNumber: 2, description: "Add onions" },
      { stepNumber: 3, description: "Add ginger-garlic paste" },
      { stepNumber: 4, description: "Add tomatoes" },
      { stepNumber: 5, description: "Add spices" },
      { stepNumber: 6, description: "Add chickpeas" },
      { stepNumber: 7, description: "Simmer and serve" },
    ],
  },
  {
    title: "Dal Makhani",
    category: "Lunch",
    description: "Creamy black lentil curry.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 60,
    benefits: "Protein-rich comfort",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak lentils overnight" },
      { stepNumber: 2, description: "Pressure cook" },
      { stepNumber: 3, description: "Heat ghee and add onions" },
      { stepNumber: 4, description: "Add ginger-garlic paste" },
      { stepNumber: 5, description: "Add tomato puree" },
      { stepNumber: 6, description: "Add cooked lentils" },
      { stepNumber: 7, description: "Simmer with cream" },
    ],
  },
  {
    title: "Rajma",
    category: "Lunch",
    description: "Kidney bean curry.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 40,
    benefits: "Fiber-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak beans overnight" },
      { stepNumber: 2, description: "Pressure cook" },
      { stepNumber: 3, description: "Heat oil and sauté onions" },
      { stepNumber: 4, description: "Add ginger and garlic" },
      { stepNumber: 5, description: "Add tomato puree" },
      { stepNumber: 6, description: "Add cooked beans" },
      { stepNumber: 7, description: "Simmer till thick" },
    ],
  },
  {
    title: "Chole Kulche",
    category: "Lunch",
    description: "Chickpea curry with soft bread.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 240,
    cookTime: 30,
    benefits: "High protein",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak chickpeas" },
      { stepNumber: 2, description: "Prepare kulche dough" },
      { stepNumber: 3, description: "Cook chickpeas" },
      { stepNumber: 4, description: "Make onion tempering" },
      { stepNumber: 5, description: "Bake kulche" },
      { stepNumber: 6, description: "Mix chickpeas with tempering" },
      { stepNumber: 7, description: "Serve together" },
    ],
  },
  {
    title: "Peas Pulao",
    category: "Lunch",
    description: "Fragrant basmati rice with peas.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 25,
    benefits: "Complete meal",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak rice" },
      { stepNumber: 2, description: "Heat ghee" },
      { stepNumber: 3, description: "Add spices and rice" },
      { stepNumber: 4, description: "Add water" },
      { stepNumber: 5, description: "Add peas" },
      { stepNumber: 6, description: "Bring to boil" },
      { stepNumber: 7, description: "Simmer till done" },
    ],
  },
  {
    title: "Vegetable Biryani",
    category: "Lunch",
    description: "Fragrant rice layered with vegetables.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Hard",
    servings: 4,
    prepTime: 30,
    cookTime: 45,
    benefits: "Complete meal",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak rice" },
      { stepNumber: 2, description: "Fry onions till golden" },
      { stepNumber: 3, description: "Marinate vegetables" },
      { stepNumber: 4, description: "Boil rice" },
      { stepNumber: 5, description: "Layer rice and vegetables" },
      { stepNumber: 6, description: "Add saffron" },
      { stepNumber: 7, description: "Cook covered" },
    ],
  },
  {
    title: "Paneer Do Pyaza",
    category: "Lunch",
    description: "Paneer with loads of onions.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    benefits: "Protein-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cut paneer into cubes" },
      { stepNumber: 2, description: "Cut onions into pieces" },
      { stepNumber: 3, description: "Heat oil" },
      { stepNumber: 4, description: "Add ginger-garlic paste" },
      { stepNumber: 5, description: "Add tomato puree" },
      { stepNumber: 6, description: "Add paneer and first half onions" },
      { stepNumber: 7, description: "Add remaining onions" },
    ],
  },
  {
    title: "Aloo Gobi Sabzi",
    category: "Lunch",
    description: "Stir-fried potatoes and cauliflower.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 25,
    benefits: "Easy to digest",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cut potatoes and cauliflower" },
      { stepNumber: 2, description: "Heat ghee" },
      { stepNumber: 3, description: "Add cumin seeds" },
      { stepNumber: 4, description: "Add potatoes" },
      { stepNumber: 5, description: "Add cauliflower" },
      { stepNumber: 6, description: "Add spices" },
      { stepNumber: 7, description: "Cook covered" },
    ],
  },
  {
    title: "Lentil Soup",
    category: "Lunch",
    description: "Hearty mixed lentil soup.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    benefits: "Protein-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak mixed lentils" },
      { stepNumber: 2, description: "Heat oil" },
      { stepNumber: 3, description: "Add onions, carrots, celery" },
      { stepNumber: 4, description: "Add garlic" },
      { stepNumber: 5, description: "Add lentils and broth" },
      { stepNumber: 6, description: "Boil and reduce heat" },
      { stepNumber: 7, description: "Simmer till soft" },
    ],
  },
  {
    title: "Pad Thai",
    category: "Lunch",
    description: "Stir-fried noodles with shrimp.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221fcf1f?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    benefits: "Balanced nutrition",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Soak rice noodles" },
      { stepNumber: 2, description: "Heat wok" },
      { stepNumber: 3, description: "Cook shrimp" },
      { stepNumber: 4, description: "Add tamarind and spices" },
      { stepNumber: 5, description: "Add noodles" },
      { stepNumber: 6, description: "Toss well" },
      { stepNumber: 7, description: "Serve with lime" },
    ],
  },
  {
    title: "Chicken Fried Rice",
    category: "Lunch",
    description: "Chinese-style fried rice with chicken.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "Asia",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Complete meal",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Use day-old rice" },
      { stepNumber: 2, description: "Heat wok till hot" },
      { stepNumber: 3, description: "Cook chicken" },
      { stepNumber: 4, description: "Scramble eggs" },
      { stepNumber: 5, description: "Add rice" },
      { stepNumber: 6, description: "Add vegetables and soy" },
      { stepNumber: 7, description: "Toss and garnish" },
    ],
  },
  {
    title: "Vegetable Noodle Soup",
    category: "Lunch",
    description: "Light broth with noodles and vegetables.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221fcf1f?w=600",
    state: "Asia",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    benefits: "Light and warming",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Boil vegetable broth" },
      { stepNumber: 2, description: "Add ginger and garlic" },
      { stepNumber: 3, description: "Add vegetables" },
      { stepNumber: 4, description: "Simmer for 10 minutes" },
      { stepNumber: 5, description: "Add noodles" },
      { stepNumber: 6, description: "Season with soy sauce" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },
  {
    title: "Cottage Cheese Salad",
    category: "Lunch",
    description: "Fresh greens with cottage cheese.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    benefits: "Low calorie",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Wash greens" },
      { stepNumber: 2, description: "Cut cottage cheese" },
      { stepNumber: 3, description: "Chop vegetables" },
      { stepNumber: 4, description: "Prepare dressing" },
      { stepNumber: 5, description: "Combine greens and vegetables" },
      { stepNumber: 6, description: "Top with cheese" },
      { stepNumber: 7, description: "Drizzle dressing" },
    ],
  },
  {
    title: "Fish Curry",
    category: "Lunch",
    description: "Spiced fish in coconut gravy.",
    image: "https://images.unsplash.com/photo-1568291473410-c78847b55c8f?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    benefits: "Heart-healthy",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Clean fish fillets" },
      { stepNumber: 2, description: "Heat oil" },
      { stepNumber: 3, description: "Add mustard seeds" },
      { stepNumber: 4, description: "Add onions and curry leaves" },
      { stepNumber: 5, description: "Add ginger-garlic paste" },
      { stepNumber: 6, description: "Add tomatoes and spices" },
      { stepNumber: 7, description: "Add fish and cook" },
    ],
  },
  {
    title: "Caprese Sandwich",
    category: "Lunch",
    description: "Tomato, mozzarella, basil sandwich.",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 5,
    benefits: "Fresh and simple",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Slice mozzarella" },
      { stepNumber: 2, description: "Slice tomatoes" },
      { stepNumber: 3, description: "Toast bread" },
      { stepNumber: 4, description: "Spread pesto" },
      { stepNumber: 5, description: "Layer tomato and cheese" },
      { stepNumber: 6, description: "Add basil" },
      { stepNumber: 7, description: "Drizzle vinegar" },
    ],
  },
  {
    title: "Chickpea Buddha Bowl",
    category: "Lunch",
    description: "Nutrient-packed grain bowl.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Balanced nutrition",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cook grains" },
      { stepNumber: 2, description: "Roast chickpeas" },
      { stepNumber: 3, description: "Sauté vegetables" },
      { stepNumber: 4, description: "Prepare tahini dressing" },
      { stepNumber: 5, description: "Arrange grains in bowl" },
      { stepNumber: 6, description: "Add vegetables and chickpeas" },
      { stepNumber: 7, description: "Drizzle dressing" },
    ],
  },

  // ==================== DINNER - 20 RECIPES ====================
  {
    title: "Butter Chicken",
    category: "Dinner",
    description: "Tender chicken in creamy tomato sauce.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    benefits: "High in protein",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat ghee" },
      { stepNumber: 2, description: "Add ginger-garlic paste" },
      { stepNumber: 3, description: "Add pre-cooked chicken" },
      { stepNumber: 4, description: "Add tomato puree" },
      { stepNumber: 5, description: "Stir in cream" },
      { stepNumber: 6, description: "Add spices" },
      { stepNumber: 7, description: "Simmer and serve" },
    ],
  },
  {
    title: "Paneer Tikka Masala",
    category: "Dinner",
    description: "Grilled cottage cheese in creamy tomato sauce.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 30,
    cookTime: 30,
    benefits: "Rich in calcium",
    equipment: ["Stovetop", "Oven"],
    steps: [
      { stepNumber: 1, description: "Marinate paneer in yogurt" },
      { stepNumber: 2, description: "Grill paneer" },
      { stepNumber: 3, description: "Heat ghee and sauté onions" },
      { stepNumber: 4, description: "Add ginger-garlic paste" },
      { stepNumber: 5, description: "Add tomato puree" },
      { stepNumber: 6, description: "Add cream and paneer" },
      { stepNumber: 7, description: "Simmer with fenugreek" },
    ],
  },
  {
    title: "Bengali Fish Curry",
    category: "Dinner",
    description: "Delicate fish in light mustard-based sauce.",
    image: "https://images.unsplash.com/photo-1568291473410-c78847b55c8f?w=600",
    state: "East India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    benefits: "Rich in omega-3",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat oil and add mustard seeds" },
      { stepNumber: 2, description: "Add ginger-garlic paste" },
      { stepNumber: 3, description: "Add turmeric and chili" },
      { stepNumber: 4, description: "Add tomatoes" },
      { stepNumber: 5, description: "Add fish and potatoes" },
      { stepNumber: 6, description: "Cover and cook" },
      { stepNumber: 7, description: "Serve with rice" },
    ],
  },
  {
    title: "Spaghetti Carbonara",
    category: "Dinner",
    description: "Creamy pasta with bacon and egg sauce.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221fcf1f?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    benefits: "Quick protein-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Boil spaghetti" },
      { stepNumber: 2, description: "Fry bacon" },
      { stepNumber: 3, description: "Beat eggs with cheese" },
      { stepNumber: 4, description: "Drain pasta" },
      { stepNumber: 5, description: "Toss pasta with bacon" },
      { stepNumber: 6, description: "Add egg mixture" },
      { stepNumber: 7, description: "Season and serve" },
    ],
  },
  {
    title: "Risotto ai Funghi",
    category: "Dinner",
    description: "Creamy rice with mushrooms.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "Europe",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    benefits: "Comfort food",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat broth" },
      { stepNumber: 2, description: "Sauté mushrooms" },
      { stepNumber: 3, description: "Toast rice" },
      { stepNumber: 4, description: "Add wine" },
      { stepNumber: 5, description: "Add broth gradually" },
      { stepNumber: 6, description: "Add Parmesan" },
      { stepNumber: 7, description: "Stir in mushrooms" },
    ],
  },
  {
    title: "Beef Stir Fry",
    category: "Dinner",
    description: "Quick-cooked beef with vegetables.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "Asia",
    difficulty: "Easy",
    servings: 4,
    prepTime: 20,
    cookTime: 15,
    benefits: "Quick weeknight",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Slice beef thin" },
      { stepNumber: 2, description: "Heat wok" },
      { stepNumber: 3, description: "Cook beef" },
      { stepNumber: 4, description: "Stir fry vegetables" },
      { stepNumber: 5, description: "Add ginger and garlic" },
      { stepNumber: 6, description: "Return beef" },
      { stepNumber: 7, description: "Serve over rice" },
    ],
  },
  {
    title: "Thai Green Curry",
    category: "Dinner",
    description: "Aromatic coconut curry with green chili.",
    image: "https://images.unsplash.com/photo-1568291473410-c78847b55c8f?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Aromatic warming",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat oil" },
      { stepNumber: 2, description: "Add curry paste" },
      { stepNumber: 3, description: "Add coconut milk" },
      { stepNumber: 4, description: "Add chicken" },
      { stepNumber: 5, description: "Simmer for 15 minutes" },
      { stepNumber: 6, description: "Add vegetables" },
      { stepNumber: 7, description: "Finish with basil" },
    ],
  },
  {
    title: "Lamb Biryani",
    category: "Dinner",
    description: "Fragrant rice layered with tender lamb.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "North India",
    difficulty: "Hard",
    servings: 4,
    prepTime: 30,
    cookTime: 45,
    benefits: "Complete meal",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Marinate lamb" },
      { stepNumber: 2, description: "Fry onions" },
      { stepNumber: 3, description: "Cook lamb" },
      { stepNumber: 4, description: "Boil rice" },
      { stepNumber: 5, description: "Layer meat and rice" },
      { stepNumber: 6, description: "Add saffron" },
      { stepNumber: 7, description: "Seal and cook" },
    ],
  },
  {
    title: "Tandoori Chicken",
    category: "Dinner",
    description: "Yogurt-marinated grilled chicken.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 480,
    cookTime: 30,
    benefits: "Protein-rich",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Mix yogurt with spices" },
      { stepNumber: 2, description: "Marinate chicken" },
      { stepNumber: 3, description: "Preheat oven" },
      { stepNumber: 4, description: "Arrange chicken on tray" },
      { stepNumber: 5, description: "Brush with oil" },
      { stepNumber: 6, description: "Bake for 20-25 minutes" },
      { stepNumber: 7, description: "Serve with salad" },
    ],
  },
  {
    title: "Baked Salmon",
    category: "Dinner",
    description: "Herb-crusted baked salmon.",
    image: "https://images.unsplash.com/photo-1580959375944-abd7e991fad6?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    benefits: "Heart-healthy",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Preheat oven" },
      { stepNumber: 2, description: "Place salmon on parchment" },
      { stepNumber: 3, description: "Brush with oil" },
      { stepNumber: 4, description: "Season with herbs" },
      { stepNumber: 5, description: "Add lemon slices" },
      { stepNumber: 6, description: "Bake for 15-20 minutes" },
      { stepNumber: 7, description: "Serve with vegetables" },
    ],
  },
  {
    title: "Vegetable Moussaka",
    category: "Dinner",
    description: "Layered eggplant and tomato dish.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600",
    state: "Europe",
    difficulty: "Medium",
    servings: 4,
    prepTime: 30,
    cookTime: 45,
    benefits: "Hearty vegetarian",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Slice and fry eggplant" },
      { stepNumber: 2, description: "Prepare tomato sauce" },
      { stepNumber: 3, description: "Make béchamel" },
      { stepNumber: 4, description: "Layer vegetables" },
      { stepNumber: 5, description: "Repeat layers" },
      { stepNumber: 6, description: "Top with cheese" },
      { stepNumber: 7, description: "Bake at 180°C" },
    ],
  },
  {
    title: "Shrimp Scampi",
    category: "Dinner",
    description: "Garlic butter shrimp pasta.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221fcf1f?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Quick elegant",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cook pasta" },
      { stepNumber: 2, description: "Heat butter and oil" },
      { stepNumber: 3, description: "Cook shrimp" },
      { stepNumber: 4, description: "Add shrimp" },
      { stepNumber: 5, description: "Add white wine" },
      { stepNumber: 6, description: "Toss paste into skillet" },
      { stepNumber: 7, description: "Garnish and serve" },
    ],
  },
  {
    title: "Mushroom Risotto",
    category: "Dinner",
    description: "Creamy rice with sautéed mushrooms.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "Europe",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    benefits: "Vegetarian comfort",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat broth" },
      { stepNumber: 2, description: "Sauté mushrooms" },
      { stepNumber: 3, description: "Toast rice" },
      { stepNumber: 4, description: "Add white wine" },
      { stepNumber: 5, description: "Add broth gradually" },
      { stepNumber: 6, description: "Add Parmesan" },
      { stepNumber: 7, description: "Stir in mushrooms" },
    ],
  },
  {
    title: "Chicken Teriyaki",
    category: "Dinner",
    description: "Glazed chicken in sweet and savory sauce.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
    state: "Asia",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Quick glazed",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Mix glaze" },
      { stepNumber: 2, description: "Cut chicken pieces" },
      { stepNumber: 3, description: "Heat skillet" },
      { stepNumber: 4, description: "Cook chicken first side" },
      { stepNumber: 5, description: "Flip chicken" },
      { stepNumber: 6, description: "Pour glaze" },
      { stepNumber: 7, description: "Serve over rice" },
    ],
  },
  {
    title: "Vegetable Stir Fry",
    category: "Dinner",
    description: "Colorful mixed vegetables in soy sauce.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600",
    state: "Asia",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Quick colorful",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Prep vegetables" },
      { stepNumber: 2, description: "Heat wok" },
      { stepNumber: 3, description: "Stir fry vegetables" },
      { stepNumber: 4, description: "Add ginger and garlic" },
      { stepNumber: 5, description: "Add soy sauce" },
      { stepNumber: 6, description: "Toss for 2-3 minutes" },
      { stepNumber: 7, description: "Serve over rice" },
    ],
  },
  {
    title: "Chicken Alfredo",
    category: "Dinner",
    description: "Creamy pasta with grilled chicken.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221fcf1f?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Creamy comfort",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cook fettuccine" },
      { stepNumber: 2, description: "Grill chicken" },
      { stepNumber: 3, description: "Melt butter" },
      { stepNumber: 4, description: "Add garlic" },
      { stepNumber: 5, description: "Add cream" },
      { stepNumber: 6, description: "Add Parmesan" },
      { stepNumber: 7, description: "Top with chicken" },
    ],
  },
  {
    title: "Thai Red Curry",
    category: "Dinner",
    description: "Rich coconut curry with red chili.",
    image: "https://images.unsplash.com/photo-1568291473410-c78847b55c8f?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Rich and warming",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Heat oil" },
      { stepNumber: 2, description: "Fry curry paste" },
      { stepNumber: 3, description: "Add coconut milk" },
      { stepNumber: 4, description: "Add chicken" },
      { stepNumber: 5, description: "Simmer 15 minutes" },
      { stepNumber: 6, description: "Add vegetables" },
      { stepNumber: 7, description: "Serve with rice" },
    ],
  },

  // ==================== SNACK - 20 RECIPES ====================
  {
    title: "Dhokla",
    category: "Snack",
    description: "Steamed spongy savory cake from chickpea flour.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "West India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 240,
    cookTime: 20,
    benefits: "High protein",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Mix chickpea flour with yogurt" },
      { stepNumber: 2, description: "Add ginger and chili" },
      { stepNumber: 3, description: "Ferment overnight" },
      { stepNumber: 4, description: "Pour into mold" },
      { stepNumber: 5, description: "Steam for 15-20 minutes" },
      { stepNumber: 6, description: "Cool and cut" },
      { stepNumber: 7, description: "Temper and serve" },
    ],
  },
  {
    title: "Momos",
    category: "Snack",
    description: "Steamed dumplings with vegetable filling.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 60,
    cookTime: 30,
    benefits: "Light protein-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Prepare dough" },
      { stepNumber: 2, description: "Rest dough" },
      { stepNumber: 3, description: "Mix filling" },
      { stepNumber: 4, description: "Shape momos" },
      { stepNumber: 5, description: "Steam for 12-15 minutes" },
      { stepNumber: 6, description: "Prepare sauce" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },
  {
    title: "Spring Rolls",
    category: "Snack",
    description: "Crispy fried rolls with vegetable filling.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 30,
    cookTime: 20,
    benefits: "Crispy savory",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Prepare filling" },
      { stepNumber: 2, description: "Soak wrappers" },
      { stepNumber: 3, description: "Place filling" },
      { stepNumber: 4, description: "Roll tightly" },
      { stepNumber: 5, description: "Heat oil" },
      { stepNumber: 6, description: "Fry till golden" },
      { stepNumber: 7, description: "Serve with sauce" },
    ],
  },
  {
    title: "Pakora",
    category: "Snack",
    description: "Spiced vegetable fritters.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "Crispy light",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Mix chickpea flour" },
      { stepNumber: 2, description: "Add water for batter" },
      { stepNumber: 3, description: "Chop vegetables" },
      { stepNumber: 4, description: "Coat in batter" },
      { stepNumber: 5, description: "Heat oil" },
      { stepNumber: 6, description: "Fry till golden" },
      { stepNumber: 7, description: "Serve with chutney" },
    ],
  },
  {
    title: "Samosa",
    category: "Snack",
    description: "Crispy triangular fried pastry.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 60,
    cookTime: 30,
    benefits: "Crispy savory",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Make dough" },
      { stepNumber: 2, description: "Rest dough" },
      { stepNumber: 3, description: "Prepare filling" },
      { stepNumber: 4, description: "Roll and cut" },
      { stepNumber: 5, description: "Fold triangles" },
      { stepNumber: 6, description: "Deep fry" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },
  {
    title: "Bruschetta",
    category: "Snack",
    description: "Toasted bread with tomato and basil topping.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 10,
    benefits: "Light fresh",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Slice baguette" },
      { stepNumber: 2, description: "Brush with oil" },
      { stepNumber: 3, description: "Toast in oven" },
      { stepNumber: 4, description: "Rub with garlic" },
      { stepNumber: 5, description: "Top with tomatoes" },
      { stepNumber: 6, description: "Add basil" },
      { stepNumber: 7, description: "Serve immediately" },
    ],
  },
  {
    title: "Nachos",
    category: "Snack",
    description: "Tortilla chips with cheese and toppings.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    benefits: "Shared fun snack",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Arrange chips" },
      { stepNumber: 2, description: "Sprinkle cheese" },
      { stepNumber: 3, description: "Add jalapeños" },
      { stepNumber: 4, description: "Bake for 5-7 minutes" },
      { stepNumber: 5, description: "Top with sour cream" },
      { stepNumber: 6, description: "Add guacamole" },
      { stepNumber: 7, description: "Serve immediately" },
    ],
  },
  {
    title: "Hummus and Veggies",
    category: "Snack",
    description: "Creamy chickpea dip with fresh vegetables.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
    state: "Middle East",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 5,
    benefits: "Protein-rich",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Drain chickpeas" },
      { stepNumber: 2, description: "Blend with tahini" },
      { stepNumber: 3, description: "Add lemon and garlic" },
      { stepNumber: 4, description: "Adjust consistency" },
      { stepNumber: 5, description: "Season to taste" },
      { stepNumber: 6, description: "Wash vegetables" },
      { stepNumber: 7, description: "Arrange and serve" },
    ],
  },
  {
    title: "Garlic Bread",
    category: "Snack",
    description: "Crispy garlic-butter toasted bread.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    benefits: "Crispy aromatic",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Mix butter and garlic" },
      { stepNumber: 2, description: "Add parsley" },
      { stepNumber: 3, description: "Slice baguette" },
      { stepNumber: 4, description: "Spread butter" },
      { stepNumber: 5, description: "Wrap in foil" },
      { stepNumber: 6, description: "Bake for 10-12 minutes" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },
  {
    title: "Onion Rings",
    category: "Snack",
    description: "Crispy battered onion slices.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Crispy indulgent",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Slice onions" },
      { stepNumber: 2, description: "Prepare batter" },
      { stepNumber: 3, description: "Dip onions" },
      { stepNumber: 4, description: "Heat oil" },
      { stepNumber: 5, description: "Fry till golden" },
      { stepNumber: 6, description: "Drain well" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },
  {
    title: "Spinach Artichoke Dip",
    category: "Snack",
    description: "Creamy dip with spinach and artichoke hearts.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "North America",
    difficulty: "Medium",
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    benefits: "Creamy indulgent",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Chop spinach and artichoke" },
      { stepNumber: 2, description: "Mix with cream cheese" },
      { stepNumber: 3, description: "Add mayo and Parmesan" },
      { stepNumber: 4, description: "Season well" },
      { stepNumber: 5, description: "Transfer to dish" },
      { stepNumber: 6, description: "Top with cheese" },
      { stepNumber: 7, description: "Bake at 190°C" },
    ],
  },
  {
    title: "Mozzarella Sticks",
    category: "Snack",
    description: "Breaded and fried mozzarella cheese.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    benefits: "Crispy melty",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cut cheese into sticks" },
      { stepNumber: 2, description: "Freeze for 2 hours" },
      { stepNumber: 3, description: "Prepare breading" },
      { stepNumber: 4, description: "Coat sticks" },
      { stepNumber: 5, description: "Heat oil" },
      { stepNumber: 6, description: "Fry for 1-2 minutes" },
      { stepNumber: 7, description: "Serve with sauce" },
    ],
  },
  {
    title: "Sweet Potato Fries",
    category: "Snack",
    description: "Crispy baked sweet potato strips.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    benefits: "Healthy satisfying",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Wash potatoes" },
      { stepNumber: 2, description: "Cut into fries" },
      { stepNumber: 3, description: "Soak in water" },
      { stepNumber: 4, description: "Pat dry" },
      { stepNumber: 5, description: "Toss with oil" },
      { stepNumber: 6, description: "Bake at 200°C" },
      { stepNumber: 7, description: "Serve hot" },
    ],
  },
  {
    title: "Guacamole and Chips",
    category: "Snack",
    description: "Creamy avocado dip with crispy chips.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Mexico",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    benefits: "Nutrient-rich fresh",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Cut avocados" },
      { stepNumber: 2, description: "Scoop flesh" },
      { stepNumber: 3, description: "Mash with lime" },
      { stepNumber: 4, description: "Add vegetables" },
      { stepNumber: 5, description: "Season well" },
      { stepNumber: 6, description: "Add chips" },
      { stepNumber: 7, description: "Serve immediately" },
    ],
  },
  {
    title: "Stuffed Mushrooms",
    category: "Snack",
    description: "Baked mushrooms with herb and cheese filling.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Europe",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 25,
    benefits: "Vegetarian elegant",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Remove mushroom stems" },
      { stepNumber: 2, description: "Chop stems finely" },
      { stepNumber: 3, description: "Mix with cream cheese" },
      { stepNumber: 4, description: "Stuff caps" },
      { stepNumber: 5, description: "Arrange on tray" },
      { stepNumber: 6, description: "Top with Parmesan" },
      { stepNumber: 7, description: "Bake for 20 minutes" },
    ],
  },
  {
    title: "Korean Kimbap",
    category: "Snack",
    description: "Seaweed wrapped rice with vegetables.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 30,
    cookTime: 10,
    benefits: "Light vegetable-rich",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Cook sushi rice" },
      { stepNumber: 2, description: "Julienne vegetables" },
      { stepNumber: 3, description: "Blanch spinach" },
      { stepNumber: 4, description: "Cool ingredients" },
      { stepNumber: 5, description: "Place nori on mat" },
      { stepNumber: 6, description: "Spread rice and veggies" },
      { stepNumber: 7, description: "Roll and slice" },
    ],
  },
  {
    title: "Deviled Eggs",
    category: "Snack",
    description: "Creamy spiced egg halves.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "North America",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    benefits: "Protein-rich festive",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Boil eggs 12 minutes" },
      { stepNumber: 2, description: "Cool in ice water" },
      { stepNumber: 3, description: "Peel and halve" },
      { stepNumber: 4, description: "Scoop yolks" },
      { stepNumber: 5, description: "Mix with mayo" },
      { stepNumber: 6, description: "Season and pipe" },
      { stepNumber: 7, description: "Garnish and serve" },
    ],
  },
  {
    title: "Vietnamese Spring Rolls",
    category: "Snack",
    description: "Fresh rolls with shrimp and herbs.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Asia",
    difficulty: "Medium",
    servings: 4,
    prepTime: 20,
    cookTime: 5,
    benefits: "Light refreshing",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Soak rice paper" },
      { stepNumber: 2, description: "Cook shrimp" },
      { stepNumber: 3, description: "Arrange lettuce" },
      { stepNumber: 4, description: "Add herbs" },
      { stepNumber: 5, description: "Add shrimp and noodles" },
      { stepNumber: 6, description: "Roll tightly" },
      { stepNumber: 7, description: "Serve with sauce" },
    ],
  },
  {
    title: "Masala Dosa",
    category: "Breakfast",
    description: "Dosa with spiced potato filling and sambhar sauce.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 480,
    cookTime: 25,
    benefits: "Protein-rich, filling breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Prepare dosa batter" },
      { stepNumber: 2, description: "Heat griddle till hot" },
      { stepNumber: 3, description: "Spread thin batter layer" },
      { stepNumber: 4, description: "Add spiced potato filling" },
      { stepNumber: 5, description: "Cook till crispy" },
      { stepNumber: 6, description: "Fold in half" },
      { stepNumber: 7, description: "Serve with sambhar and chutney" },
    ],
  },
  {
    title: "French Toast",
    category: "Breakfast",
    description: "Bread dipped in egg and milk custard, fried golden.",
    image: "https://images.unsplash.com/photo-1585935924455-c7a6e54ac002?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    benefits: "Classic comfort breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Whisk eggs and milk together" },
      { stepNumber: 2, description: "Add cinnamon and sugar" },
      { stepNumber: 3, description: "Heat butter on griddle" },
      { stepNumber: 4, description: "Dip bread slices in mixture" },
      { stepNumber: 5, description: "Cook on griddle till golden" },
      { stepNumber: 6, description: "Flip and cook other side" },
      { stepNumber: 7, description: "Serve with syrup and berries" },
    ],
  },
  {
    title: "Ragi Porridge",
    category: "Breakfast",
    description: "Nutritious finger millet porridge with jaggery.",
    image: "https://images.unsplash.com/photo-1585937421945-7a71f96a4fcf?w=600",
    state: "South India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 20,
    benefits: "High in calcium and iron",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Roast ragi flour" },
      { stepNumber: 2, description: "Boil water or milk" },
      { stepNumber: 3, description: "Add roasted ragi slowly" },
      { stepNumber: 4, description: "Stir continuously" },
      { stepNumber: 5, description: "Add jaggery" },
      { stepNumber: 6, description: "Cook till thick" },
      { stepNumber: 7, description: "Serve hot with ghee" },
    ],
  },
  {
    title: "Lachcha Paratha",
    category: "Breakfast",
    description: "Flaky layered flatbread with oil brushing.",
    image: "https://images.unsplash.com/photo-1605521209583-75d256e5caf1?w=600",
    state: "North India",
    difficulty: "Medium",
    servings: 4,
    prepTime: 30,
    cookTime: 20,
    benefits: "Layered, indulgent breakfast",
    equipment: ["Stovetop"],
    steps: [
      { stepNumber: 1, description: "Make smooth dough" },
      { stepNumber: 2, description: "Rest dough for 1 hour" },
      { stepNumber: 3, description: "Roll dough thin" },
      { stepNumber: 4, description: "Brush with ghee" },
      { stepNumber: 5, description: "Roll into spiral" },
      { stepNumber: 6, description: "Coil and flatten" },
      { stepNumber: 7, description: "Cook on tawa till golden and flaky" },
    ],
  },
  {
    title: "Mint Lemonade",
    category: "Snack",
    description: "Refreshing drink with fresh mint and lemon juice.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Asia",
    difficulty: "Easy",
    servings: 4,
    prepTime: 5,
    cookTime: 5,
    benefits: "Refreshing and hydrating",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Crush fresh mint leaves" },
      { stepNumber: 2, description: "Squeeze fresh lemon juice" },
      { stepNumber: 3, description: "Mix with cold water" },
      { stepNumber: 4, description: "Add sugar or honey" },
      { stepNumber: 5, description: "Stir well" },
      { stepNumber: 6, description: "Add ice cubes" },
      { stepNumber: 7, description: "Serve immediately" },
    ],
  },
  {
    title: "Cheese and Crackers",
    category: "Snack",
    description: "Assorted cheese with crispy crackers and fruits.",
    image: "https://images.unsplash.com/photo-1599599810694-b62b0fa42e0c?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    benefits: "Easy assembly, protein-rich",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Select variety of cheeses" },
      { stepNumber: 2, description: "Slice or cube cheese" },
      { stepNumber: 3, description: "Arrange on board" },
      { stepNumber: 4, description: "Add variety of crackers" },
      { stepNumber: 5, description: "Add fresh and dried fruits" },
      { stepNumber: 6, description: "Add nuts and olives" },
      { stepNumber: 7, description: "Serve with water or wine" },
    ],
  },

  {
    title: "Lentil Chips",
    category: "Snack",
    description: "Crispy baked lentil flour wafers.",
    image: "https://images.unsplash.com/photo-1585238343270-19db339dd654?w=600",
    state: "South India",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    benefits: "High protein snack",
    equipment: ["Oven"],
    steps: [
      { stepNumber: 1, description: "Mix lentil flour with spices" },
      { stepNumber: 2, description: "Add water to make thick batter" },
      { stepNumber: 3, description: "Spread thin on baking sheet" },
      { stepNumber: 4, description: "Bake at 200°C for 10 minutes" },
      { stepNumber: 5, description: "Cut into chip shapes" },
      { stepNumber: 6, description: "Bake 10 more minutes" },
      { stepNumber: 7, description: "Cool and store" },
    ],
  },
  {
    title: "Tabbouleh",
    category: "Lunch",
    description: "Fresh herb and bulgur salad with lemon dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
    state: "Middle East",
    difficulty: "Easy",
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    benefits: "Light and refreshing",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Soak bulgur in hot water" },
      { stepNumber: 2, description: "Chop fresh parsley" },
      { stepNumber: 3, description: "Chop mint and tomatoes" },
      { stepNumber: 4, description: "Chop cucumber and onion" },
      { stepNumber: 5, description: "Mix vegetables with bulgur" },
      { stepNumber: 6, description: "Dress with lemon and oil" },
      { stepNumber: 7, description: "Chill and serve" },
    ],
  },
  {
    title: "Greek Salad",
    category: "Lunch",
    description: "Fresh salad with feta cheese and olives.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
    state: "Europe",
    difficulty: "Easy",
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    benefits: "Fresh and Mediterranean",
    equipment: ["No-Cook"],
    steps: [
      { stepNumber: 1, description: "Chop cucumbers" },
      { stepNumber: 2, description: "Chop tomatoes" },
      { stepNumber: 3, description: "Dice feta cheese" },
      { stepNumber: 4, description: "Add kalamata olives" },
      { stepNumber: 5, description: "Add red onion" },
      { stepNumber: 6, description: "Dress with oil and vinegar" },
      { stepNumber: 7, description: "Serve immediately" },
    ],
  },
];

async function seedDatabase() {
  try {
    console.log(`\n${"=".repeat(70)}`);
    console.log(`🌱 RECIPE DATABASE SEEDER - 80 RECIPES (20 PER CATEGORY)`);
    console.log(`${"=".repeat(70)}`);
    console.log(`📊 Total recipes to seed: ${RECIPES.length}\n`);

    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(
        process.env.MONGODB_URI || "mongodb://localhost:27017/recipe-finder",
      );
      console.log("✅ Connected to MongoDB\n");
    }

    let adminUser = await User.findOne({ email: "admin@recipefinder.com" });
    if (!adminUser) {
      console.log("👤 Creating admin user...");
      adminUser = await User.create({
        name: "Recipe Finder Admin",
        email: "admin@recipefinder.com",
        password: "admin123",
        role: "admin",
      });
      console.log("✅ Admin user created\n");
    }

    let successCount = 0;
    let failCount = 0;
    const categoryStats = { Breakfast: 0, Lunch: 0, Dinner: 0, Snack: 0 };

    console.log(`📝 Seeding ${RECIPES.length} recipes...`);
    for (const recipe of RECIPES) {
      try {
        await Recipe.create({ ...recipe, user: adminUser._id });
        successCount++;
        if (categoryStats[recipe.category] !== undefined) {
          categoryStats[recipe.category]++;
        }
      } catch (error) {
        failCount++;
        console.error(`❌ Failed to seed "${recipe.title}": ${error.message}`);
      }
    }

    await mongoose.connection.close();

    console.log(`\n${"=".repeat(70)}`);
    console.log(`✅ Successfully: ${successCount} | ❌ Failed: ${failCount}`);
    console.log(`📊 Total in database: ${successCount} recipes`);
    console.log(`\n📋 RECIPES BY CATEGORY:`);
    console.log(`   🍳 Breakfast: ${categoryStats.Breakfast}`);
    console.log(`   🍽️  Lunch: ${categoryStats.Lunch}`);
    console.log(`   🍴 Dinner: ${categoryStats.Dinner}`);
    console.log(`   🥨 Snack: ${categoryStats.Snack}`);
    console.log(`${"=".repeat(70)}\n`);
  } catch (error) {
    console.error("❌ Seeding error:", error.message);
    process.exit(1);
  }
}

seedDatabase();
